import '../presentation/model/chat_list.dart';

final List<ChatList> mockChatList = [
  ChatList(
    id: "1",
    name: 'Alexander Wright',
    lastMessageTime: DateTime.now().subtract(const Duration(minutes: 2)),
    profilePicUrl: "https://unsplash.com",
    lastMessage: "Are we still on for the sync session at 10?",
    unreadCount: 0,
  ),
  ChatList(
    id: "2",
    name: 'Elena Rostova',
    lastMessageTime: DateTime.now().subtract(const Duration(hours: 1)),
    profilePicUrl: "https://unsplash.com",
    lastMessage: "The new glassmorphism layouts look incredibly clean.",
    unreadCount: 3,
  ),
  ChatList(
    id: "3",
    name: "Design Critique Group",
    lastMessageTime: DateTime.now().subtract(const Duration(hours: 4)),
    profilePicUrl: "https://unsplash.com",
    lastMessage: "Marcus: Let’s stick strictly to black and white typography.",
    unreadCount: 0,
  ),
  ChatList(
    id: "4",
    name: "Devon Lane",
    lastMessageTime: DateTime.now().subtract(const Duration(days: 1)),
    profilePicUrl: "https://unsplash.com",
    lastMessage: "Main navigation architecture is fully merged.",
    unreadCount: 1,
  ),
  ChatList(
    id: "5",
    name: "Sarah Jenkins",
    lastMessageTime: DateTime.now().subtract(const Duration(days: 3)),
    profilePicUrl: "https://unsplash.com",
    lastMessage: "Sent you the updated API endpoints file.",
    unreadCount: 0,
  ),
  ChatList(
    id: "1",
    name: 'Alexander Wright',
    lastMessageTime: DateTime.now().subtract(const Duration(minutes: 2)),
    profilePicUrl: "https://unsplash.com",
    lastMessage: "Are we still on for the sync session at 10?",
    unreadCount: 0,
  ),
  ChatList(
    id: "2",
    name: 'Elena Rostova',
    lastMessageTime: DateTime.now().subtract(const Duration(hours: 1)),
    profilePicUrl: "https://unsplash.com",
    lastMessage: "The new glassmorphism layouts look incredibly clean.",
    unreadCount: 3,
  ),
  ChatList(
    id: "3",
    name: "Design Critique Group",
    lastMessageTime: DateTime.now().subtract(const Duration(hours: 4)),
    profilePicUrl: "https://unsplash.com",
    lastMessage: "Marcus: Let’s stick strictly to black and white typography.",
    unreadCount: 0,
  ),
  ChatList(
    id: "4",
    name: "Devon Lane",
    lastMessageTime: DateTime.now().subtract(const Duration(days: 1)),
    profilePicUrl: "https://unsplash.com",
    lastMessage: "Main navigation architecture is fully merged.",
    unreadCount: 1,
  ),
  ChatList(
    id: "5",
    name: "Sarah Jenkins",
    lastMessageTime: DateTime.now().subtract(const Duration(days: 3)),
    profilePicUrl: "https://unsplash.com",
    lastMessage: "Sent you the updated API endpoints file.",
    unreadCount: 0,
  ),
  ChatList(
    id: "1",
    name: 'Alexander Wright',
    lastMessageTime: DateTime.now().subtract(const Duration(minutes: 2)),
    profilePicUrl: "https://unsplash.com",
    lastMessage: "Are we still on for the sync session at 10?",
    unreadCount: 0,
  ),
  ChatList(
    id: "2",
    name: 'Elena Rostova',
    lastMessageTime: DateTime.now().subtract(const Duration(hours: 1)),
    profilePicUrl: "https://unsplash.com",
    lastMessage: "The new glassmorphism layouts look incredibly clean.",
    unreadCount: 3,
  ),
  ChatList(
    id: "3",
    name: "Design Critique Group",
    lastMessageTime: DateTime.now().subtract(const Duration(hours: 4)),
    profilePicUrl: "https://unsplash.com",
    lastMessage: "Marcus: Let’s stick strictly to black and white typography.",
    unreadCount: 0,
  ),
  ChatList(
    id: "4",
    name: "Devon Lane",
    lastMessageTime: DateTime.now().subtract(const Duration(days: 1)),
    profilePicUrl: "https://unsplash.com",
    lastMessage: "Main navigation architecture is fully merged.",
    unreadCount: 1,
  ),
  ChatList(
    id: "5",
    name: "Sarah Jenkins",
    lastMessageTime: DateTime.now().subtract(const Duration(days: 3)),
    profilePicUrl: "https://unsplash.com",
    lastMessage: "Sent you the updated API endpoints file.",
    unreadCount: 0,
  ),
];
